# Настройки для проекта YAxUnit
# Профиль: yaxunit

# Базовые настройки приложения
app:
  id: yaxunit
  format: EDT
  
  # Набор исходного кода проекта
  source-set:
    # Основная конфигурация YAxUnit (движок)
    - path: "fixtures/demo-configuration"
      name: configuration
      type: "CONFIGURATION"
      purpose: [ "TESTS" ]
    
    # Основная конфигурация YAxUnit (движок)
    - path: "exts/yaxunit"
      name: yaxunit
      type: "EXTENSION"
      purpose: [ "MAIN", "YAXUNIT" ]
    
    # Основная конфигурация YAxUnit (движок)
    - path: "exts/smoke"
      name: smoke
      type: "EXTENSION"
      purpose: [ "MAIN", "YAXUNIT" ]

    # Тесты YAxUnit
    - path: "tests"
      name: tests
      type: "EXTENSION"
      purpose: [ "TESTS" ]
  
  # Настройки инструментов
  tools:
    # Тип сборщика: DESIGNER или IBMCMD
    builder: DESIGNER
    # Настройки EDT CLI
    edt-cli:
      auto-start: true
      startup-timeout-ms: 300000 # 5 минут
      command-timeout-ms: 600000 # 10 минут
      ready-check-timeout-ms: 5000